<a href="https://colab.research.google.com/github/Rajneeshzytox/all-ml-ai-projects/blob/main/iris_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Classifying Iris Species


## Loading The Data

In [2]:
# iris dataset
from sklearn.datasets import load_iris
data = load_iris()
# this object returns dictionary with key and values

In [3]:
# Getting the leys
print(f"{'Keys of iris dataset':_^30}")
print(data.keys())


_____Keys of iris dataset_____
dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [4]:
print(data['DESCR'])

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Cr

In [5]:
# target names
print(data.target_names)
print(f"{'target shape':-^30}\n {data['target'].shape} data ")
print(f"{'target data type':-^30}\n {type(data['target_names'])}")

# print(data.target)

['setosa' 'versicolor' 'virginica']
---------target shape---------
 (150,) data 
-------target data type-------
 <class 'numpy.ndarray'>


In [6]:
# features names
print(data.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [7]:
#data info
print(f"{'data shape':-^30}\n {data['data'].shape} \n")
print(f"{'data type':-^30}\n {type(data['data'])} \n")
print(f"{'first 5 data':-^30}\n {data['data'][:5]} \n")

----------data shape----------
 (150, 4) 

----------data type-----------
 <class 'numpy.ndarray'> 

---------first 5 data---------
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]] 



## Data Split train and tsted

In [8]:
from sklearn.model_selection import train_test_split

X = data['data']
y = data['target']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)


In [9]:
print(f"{X_train.shape} X_train")
print(f"{X_test.shape} X_test")
print(f"{y_train.shape} X_test")
print(f"{y_test.shape} X_test")

(112, 4) X_train
(38, 4) X_test
(112,) X_test
(38,) X_test


## Model define and train

In [10]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)

In [11]:
# fit
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=1)

## Predictions

In [12]:
preds = knn.predict(X_test)


print("predictions : ", preds[:10]) # getting first 10 sample of predictions
print("actual val : ",  y_test[:10])


# mean test score
print("test mean score: ", np.mean(preds == y_test))

predictions :  [2 1 0 2 0 2 0 1 1 1]
actual val :  [2 1 0 2 0 2 0 1 1 1]
test mean score:  0.9736842105263158


## Test Score

In [13]:
knn.score(X_test, y_test)

0.9736842105263158